spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shareit
    password: test
    username: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect